OBJS = battleShipClass.o battleShip.o
CPPFLAGS = -std=c++11
PROG = hash
CC = g++

$(PROG): $(OBJS)
	$(CC) -o $(PROG) $(OBJS)
	
battleShipClass.o: battleShipClass.h battleShipClass.cpp
	$(CC) $(CPPFLAGS) -c battleShipClass.cpp
	
battleShip.o: battleShip.cpp
	$(CC) $(CPPFLAGS) -c battleShip.cpp
	
clean:
	$(RM) $(PROG) $(OBJS)


